// <auto-generated />
using BioTechAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BioTechAPI.Migrations
{
    [DbContext(typeof(BioTechContext))]
    partial class BioTechContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BioTechAPI.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Education");

                    b.Property<string>("Experience");

                    b.Property<string>("PostDate");

                    b.Property<string>("Qualifications");

                    b.Property<string>("Responsibilites");

                    b.Property<string>("Schedule");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
